set(_CATKIN_CURRENT_PACKAGE "gripit")
set(gripit_VERSION "0.0.1")
set(gripit_MAINTAINER "Yannick Roberts <yannick.oderri@gmail.com>")
set(gripit_PACKAGE_FORMAT "2")
set(gripit_BUILD_DEPENDS "rospy" "python-numpy" "python-future" "python-skimage")
set(gripit_BUILD_EXPORT_DEPENDS "rospy" "pyqt5-dev-tools")
set(gripit_BUILDTOOL_DEPENDS "catkin")
set(gripit_BUILDTOOL_EXPORT_DEPENDS )
set(gripit_EXEC_DEPENDS "rospy" "python-skimage" "python-future" "python-numpy" "python-rosdep" "pyqt5-dev-tools")
set(gripit_RUN_DEPENDS "rospy" "python-skimage" "python-future" "python-numpy" "python-rosdep" "pyqt5-dev-tools")
set(gripit_TEST_DEPENDS )
set(gripit_DOC_DEPENDS )
set(gripit_URL_WEBSITE "")
set(gripit_URL_BUGTRACKER "")
set(gripit_URL_REPOSITORY "")
set(gripit_DEPRECATED "")